### ISSUE TITLE
how can I disable text color on Select description text?

### ISSUE THREAD

**Issue by eliranwong** [go-survey/survey#477]
how can I disable text color on Select description text?

currently, it is blue in color.  I do not want text color in some cases.

Appreciate your good work.  Thank you.

**Comment by mislav** [comment]
Hi, the only way right now is to override the `survey.SelectQuestionTemplate` string: https://github.com/go-survey/survey/blob/fa37277e6394c29db7bcc94062cb30cd7785a126/select.go#L72
